# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_test
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r100mm
bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r100mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r100mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r100m
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r50mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r50mmm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r50mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r50mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r20mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r20mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r20mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r20mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r10mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r10mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r10mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r10m
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r5mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r5mmm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r5mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r5mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r2mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r2mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r2mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r2mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/striped_line_r1mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_line_r1mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/white_line_r1mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r1mm
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/black_line_r0_01
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_cube
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_sphere
# bash run_exps.bash ~/Datasets/NeRF/nerf-geometry-analysis/checkered_plane